os: osx
language: swift
osx_image: xcode9

script:
  - xcodebuild -scheme CollectionKit -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6S,OS=10.3' build test

cache:
  directories:
  - Carthage

before_install:
  - carthage bootstrap --verbose --no-use-binaries --platform iOS --cache-builds

after_success:
  - bash <(curl -s https://codecov.io/bash)